language: java
dist: trusty
os: linux

jdk:
  - openjdk11

cache:
  directories:
    - "$HOME/.m2"

install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

before_install:
    - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXEC --import; fi
    - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXEC --import-ownertrust; fi

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    on:
      branch: master

env:
    global:
     # GPG_EXEC
    - secure: "a3SeoaB/WOjyvULnBwelpse4AkvAVjdluWPCZsl7ns8uRAPYC763Gi12dBZzCUOt/NkgvqqS3qAE2k/ng+G17iNjZqMiLmZD5dOIlKjZnbj36GTUkL7EXuJv0o1ntOqdjGbLsFnAGDUTlu6NXITLxQq0AP4GkvgQnLcciB+JiL3HQumw8C5yn0I/V+zpUXVwiZ/eo9Qe+QLeACppFgKd84O2itzpGOZtz8UZ14zFXGwb03w5a+psm4adcasgZvfkc9lc/XzORaUa0Z2mSBsPfqISPskZgUmKI1OlY8roK5v/FU9G+ImkuUwqexMvPmmTmhjywGQZ/WrioPhIXBjXR1+Ybb2knVBLUVcHIcLYHipTJsQHypG/v8gwVhk34V9hJj+NXtVKaueRv7hQsY1waYDLuAPlogfjMZ6M5ZBsAunbr2t2CSdz47ABz3+VR8tyAnZRwJFQRCYABaVUmtx/tmxSuIl9Vj3jEKtdBQ7mFfnf2mRP0ohUcJPj0FXfYC8xjOg75a8ojimH+UjMQYBL1CljAWiXsnDdQOENc+gzsetYdxSKmsTQdO1OUtM9kju+O6K99cQwE+BCXvny6N4cZgfz1aBnNtZKPOf8Xu96ZWh3bTOFO5qQjwqUoF6/BYdsdXH0+KPGO0uV+7euNaVXio66PZY2ABa5pWicr90tCTc="
     # GPG_OWNERTRUST
    - secure: "BeZvgqU2Yd8YjNcK3q43u1KykNTN7pZY3zojeYsrVvuPDwv8rVuzMATa9urhQ/gIz18xZYXltrpRo4St7LYfjDCWf2tn2dMsQsRiQCeZ45k6l/qVMlto1Y5uoCujraqqiKwOHdYe01HthqQ7OggXcAWfTl66tU2Hc0dOqWZKwM5kiFpdFlArQTtlqSVnWCLoAmubkOeJxbGRWQRCkzShm7czESu4gfygkjDhXfi42EGIAlfm7tH8BXFGnBn+hGA9CaUZ0ZfXSu2cdRU5usUTqUgtt9LJ5VJFa392bJ+m46iNRHCHLwbqDqMf4tIVyn/n030cbsvXU4uEnmo4gcDYmZw/psD84HlWpCKYaaM9Vma9kWzvhvDlg96QIutO7hfnfmH7UVXrGRa190kygOfjRT6IppaFEJ1wEU0qBjsUxQgFoBVE868MpSG+dzIA1YsJ4CZRMaNS2xB+DtDNnXi3bldLwMBFChQybIgLUxRxHz3+d0Pk2c8QRvCQtO8VHlYGGTAYvfeeKuqcsWqSWWi6lIGYyGQgvWy0ju6XcDlrCfxrm+6xxnN5y5Bl0/sKU3EFw8lBhIIFe4ud9o/On6m1C4k8nYrHtLbsyH5WjzilwVpWwdjNB051uubcpyRSTLRLj2hGCljgdpP9SG0/Mv2WF2nbLKVHB2Mxrmh+zODEOMM="
     # GPG_PASSPHRASE
    - secure: "KhgPFPnopq3sUfQ+jv3DQQgGOiYGr8SPso+uqOeAvFJmQB/leeU4SxQAVBrJ+mRel9LvYmnpkvA6NlZsRkN7y07Ez+dE7z4HFTOROasXhA67AQoOdePqbnp+4197UpYiEl+vLH8/bnZmGVA6CcglCQY2xPde1tjG3NpgCfzhAjQxKaYuYrhdTODB551Rcr0Z5pWgommJXGybqWFJ1ZUtLbmlgKirUpd/7jRcgerXCXL7oJy2CnlEDGBmczkxR9Zvd/GjK7V0J+29OtcCT2DGbiqLM+jzxBNL7UrNTYHfRl1GsnOaKv4R1q0lUN7Ke4yNAfCmVVkkz2UB1ecZmpjNmrmp0ecfXV13EtZH7kxvSGB/9LB9v4KqcMqz/p24L6VLov5wKnFsyXwsr49rPe0UeS6ECG/5PQk+BNPSF7cXLBSDWU7T0+601ZTArzGGYWSA5OWQiJla634z7v16eAGsJ9VS4/vdXJo7uXkHfIxkVvzE9F8GwoMWTv2fTEdxUa/DGY7R4CQoF3UKPUtjCa7fzT3quvq7YOTh3o/T4gZ+RCY1rEX6Iialzr0pAsoErVixqlOMRvq5k0jJzlsHU0lzLErJxyMI9E0ymRtrycgVi4hSO216bVg+8kZJbbpZqRIr1GriY+msUuYGpDDLTU7c/A6B5Pfx6V1oWP9c4sm2cE8="
     # GPG_SECRET_KEYS (set online value too large)
     # NEXUS_PASSWORD
    - secure: "Fix+SyneqNe8dv3SdDgTMBbdeKPP+TFNKECPELgSHkTAB+pQOwQtyCS+9ZK3BDyz5UCgRjD/fl0evl7LzOWGOch6nMVYGyyFEt9dlnKa+BRotsIfuThPt6dLQVGZvLzyFBjfJwBxnRdiLnG3RG/s+krNzr9sMvKUFG/5qsQ8iSCtdqUqfJX51aBbN9MLueRqrsPJa1eoPSOUFNu3LLUILHg8qnilklat4qVXFGzF2whCKMlQcPj5B4BFJ9xRH6tyGFrHoI3rhJ2sgGluxcHhMaUE31yVZQE51RCTi/mB4xkiKL7P0xejGrG4UiUUGh+Rku4fZIqGZRbO2BwI+ZMhHKNh4ZJKMoRfyBxPOIsBfxoLeUADJ+OIIT9yviCvc+fksa/wBH6AI7Qri0j99h5RlaPJjIaM7fF87FeR3828IZaX1a0rC4bvujC59TmR656nv5ib1iJVZ2MoxHzb5gNoODmNAXxtuDTF0pG5yuNsMcnvxmNEMs7zXXJqiawfe4wEUjQVJn53ecusoOrgiCGdhs2h7vrsGf5V0k83aYhb4TQ/6X+yDEMNtAGFEjBbEk6+tfXvwG/EunJwS/StELSy/W8KUDGLlAJvPS1yj0lQuI0uumtQDjWkqjqIjSLKh2PlsWeJn5uKzbeTGqWaxb7OebfOCH2WEN03mg/VCeghBl4="
     # NEXUS_USERNAME
    - secure: "erT+vs1GRxaRQsYYxvh1ds6qooZb2USZlivvsxtMIrgoBHrk6dPfq/v4kwsW8ysd6FnR+MpE8cFevR7AOdhoJZMvNXVYSQdunugSEndP4GXYSIT398j89D22BDwKn3Mu1woyMXAAp112VTV7+JP7CFwYgWTD3xPAkLJmvCInD2Fb+cWh7hZor6D6B4eMXBzMb8F8DE80I/FkdN7YRhbATk2beT0p3R1hAtY/At/FzeYDhoyOoDX1l7chiT/EBcYkI980lOOzL/BYaFA35Fbg//OwS0grF2xyvbKCvJ/4QNFeFtD1GPaElqRiKXTMOzkN8m7Escr7PtF8mzBoHn/kIZuiDfHhs5pnT89cILKvVuwmnaab+1UsDPx/4g0M2rg03xrdnEkui0MEguFiDCeL+GdepPu9l5sG4F1THkSvJ1qXfA82sR1p3qX5zvpnpkJu2jCJ5bBu0o/InuWLtZBgwj5H0mZSnmgjkxbfMX+5HJL8kqv/YSlNcYetaaZnMa/52PBKA//UMkruikdXhK5UNBe4iIH7z2L57LVszIxj3e5FE2d408hvoKaSIGKe2IdweRc9Voadsvj5T6KD6ds/xjp6LGpxVWMFfvrbHX4lCojD7sFyiuXzgIDZv2Ihy94upRoYMKncvHgWMoqcVvz7/52xxXWLH5JGoFhLlsYXOns="